export const menuTemp = [
  {
    id: 1,
    foodName: "Teh Hangat",
    description: "Nasi + Ayam + Sayur + Es teh",
    images: "/images/menu/gbr1.jpg",
    price: 3500,
    categori: "drink",
    date: "22 Desember 2022",
  },
  {
    id: 2,
    foodName: "Nasi Kuning Telur",
    description: "Nasi + Ayam + Sayur + Es teh",
    images: "/images/menu/gbr2.jpg",
    price: 6000,
    categori: "food",
    date: "10 Januari 2024",
  },
  {
    id: 3,
    foodName: "Ikan Bandeng Bakar Saos Tiram",
    description: "Nasi + Ayam + Sayur + Es teh",
    images: "/images/menu/gbr3.jpg",
    price: 20000,
    categori: "food",
    date: "10 Januari 2024",
  },
  {
    id: 4,
    foodName: "Ayam Geprek Sambal Matah",
    description: "Nasi + Ayam + Sayur + Es teh",
    images: "/images/menu/gbr4.jpg",
    price: 29000,
    categori: "food",
    date: "10 Januari 2024",
  },
  {
    id: 5,
    foodName: "Nasi Goreng Cumi Jakarta",
    description: "Nasi + Ayam + Sayur + Es teh",
    images: "/images/menu/gbr5.jpg",
    price: 17000,
    categori: "food",
    date: "10 Januari 2024",
  },
];
